version: "3.8"

services:
    traefik:
        image: "traefik:v3.3"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
            - "--ping=true"
            - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    whoami:
        image: "traefik/whoami"
        container_name: "whoami-service"
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
        - "traefik.http.routers.whoami.entrypoints=web"
    vscode:
        build:
            context: ./vscode
            dockerfile: Dockerfile
            args:
                USER: ${USER}
                UID: ${UID}
                GID: ${GID}
        container_name: "vscode-service"
        env_file:
            - .env
        environment:
            - PASSWORD=${PASSWORD}
            - DOCKER_USER=${USER}
            - HTTPS_ENABLED=${HTTPS_ENABLED}
            - APP_PORT=${APP_PORT}
            - APP_BIND_HOST=${APP_BIND_HOST}
            - LAB_REPO=${LAB_REPO}
            - EXTENSIONS=${EXTENSIONS}
        user: "${UID}:${GID}"
        volumes:
            - $PWD/workspace:/home/coder/workspace
            - $PWD/config:/home/coder/.config
            - $PWD/certs:/home/coder/.certs
        ports:
            - "${APP_PORT}:${APP_PORT}"
        labels:
            - "traefik.enable=true"
            # Docker Swarm - "traefik.http.routers.vscode.rule=Host(`vscode-{{.Task.Slot}}.localhost`)"
            - "traefik.http.routers.vscode.rule=Host(`vscode.localhost`)"
            - "traefik.http.services.vscode.loadbalancer.server.port=${APP_PORT}"
        deploy:
            replicas: 1
