version: '3'
services:
    vscode:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER: $USER
                UID: $UID
                GID: $GID
        environment:
            - PASSWORD=htplus
            - DOCKER_USER=${USER}
            - HTTPS_ENABLED=false
            - APP_PORT=8443
            - APP_BIND_HOST=0.0.0.0
            - LAB_REPO=https://github.com/oxygen-batd/oxyLamportSend
            - EXTENSIONS=MS-CEINTL.vscode-language-pack-ja
        user: "$UID:$GID"
        # user: "root"
        volumes:
            - $PWD/workspace:/home/coder/workspace
            - $PWD/config:/home/coder/.config
            - $PWD/certs:/home/coder/.certs
        ports:
            - 8443:8443
