version: '3'
services:
    vscode:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER: $USER
                UID: $UID
                GID: $GID
        environment:
            - PASSWORD=htplus
            - DOCKER_USER=${USER}
            - HTTPS_ENABLED=false
            - APP_PORT=8443
            - APP_BIND_HOST=0.0.0.0
            - LAB_REPO=https://github.com/oxygen-batd/oxyLamportSend
            # - EXTENSIONS=ms-python.python
        user: "$UID:$GID"
        volumes:
            - ./workspace:/home/coder/workspace
            - ./config:/home/coder/.config
            - ./certs:/home/coder/.certs
        ports:
            - 8443:8443
