version: "3.8"

services:
    traefik:
        image: "traefik:v3.3"
        command:
            - "--api=true"
            - "--log.level=INFO"
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--entrypoints.web.address=:80" # HTTP for VSCode
            - "--entrypoints.traefik.address=:8080"
            # HTTPS
            # - "--entrypoints.websecure.address=:443"
            # - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
            # - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
            # - "--certificatesresolvers.myresolver.acme.email=htplus@gmail.com"
            # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "80:80"
            - "8080:8080"
            # - "443:443"  # HTTPS
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
            - "./logs:/var/log/traefik"
            # - "./letsencrypt:/letsencrypt"       # HTTPS
        environment:
            - TRAEFIK_API_DASHBOARD=true
            - TRAEFIK_API_INSECURE=true
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: "512M"
                reservations:
                    cpus: "0.1"
                    memory: "128M"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
            - "traefik.http.routers.api.service=api@internal"
            - "traefik.http.routers.api.entrypoints=traefik"
            # Auth dashboard:
            # - "traefik.http.routers.api.middlewares=auth"
            # - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$H6uskkkW$IgXLP..."
        networks:
            - web
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

volumes:
    logs:
        # letsencrypt:                             # HTTPS

networks:
    web:
        driver: overlay
