apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: codercom/code-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /home/coder/project
              name: code-server-data
            - name: config-volume
              mountPath: /home/coder/.config/code-server/config.yaml
              subPath: config.yaml
      volumes:
        - name: code-server-data
          persistentVolumeClaim:
            claimName: code-server-pvc
        - name: config-volume
          configMap:
            name: code-server-config
