apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vscode-workspace-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vscode-config-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vscode-certs-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
    storageClassName: standard
