apiVersion: v1
kind: Service
metadata:
  name: code-server-service
  namespace: default
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer