apiVersion: v1
kind: Service
metadata:
  name: code-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  sessionAffinity: ClientIP  # Giữ kết nối cố định với một pod
