apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
    name: vscode-tls-options
    namespace: default
spec:
    minVersion: VersionTLS12
    cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
