http:
    routers:
        code-server-router:
        rule: "Host(vscode.localhost`)"
        entryPoints:
            - websecure
        tls:
            certResolver: myresolver
        service: code-server-service

    services:
        code-server-service:
        loadBalancer:
            servers:
                - url: "http://vscode.localhost:8080"