global:
    checkNewVersion: true

entryPoints:
  web:
    address: ":80"
    http:
        redirections:
            entryPoint:
            to: websecure
            scheme: https
    websecure:
        address: ":443"

providers:
    kubernetesCRD: {}
    kubernetesIngress: {}

certificatesResolvers:
    myresolver:
        acme:
        email: vscode.localhost
        storage: "/letsencrypt/acme.json"
        tlsChallenge: true